### ISSUE TITLE
Support for a more terminal-like experience

### ISSUE THREAD

**Issue by alice-i-cecile** [RichoDemus/bevy-console#11]
This is useful for making "terminal games" that can be run on the web.

Desired features:

- Console cannot be moved or closed
- Console typically fills screen, and resizes to it
- Console size can still be set, in order to share the screen

Stretch goals:

- Ability to seamlessly change out the terminal backend for a Real Terminal
- Basic turn-based game architecture

See fork created [here](https://github.com/leafwing-studios/leafwing_terminal) for Bevy Jam 1.0 :)

**Comment by Victor-N-Suadicani** [comment]
Personally feel this would belong better as an entirely separate plugin. Feel like the goals of this one should stay as a "debug" console only.
