### ISSUE TITLE
Hide ugly `add_terminal_command` type parameters

### ISSUE THREAD

**Issue by alice-i-cecile** [RichoDemus/bevy-console#13]
By wrapping this method in a public method with only the single useful type parameter, you can create a prettier API:

```rust
trait ActionExt {
    fn add_action<TC: Commandliket>(&mut self, action: Action);
}

impl ActionExt for App {
    fn add_action<TC: Commandlike>(&mut self, action: Action) {

        self.add_terminal_command::<TC, _, _>(start_action_system);
    }
}
```

**Comment by makspll** [comment]
I don't think we can completely reduce the type parameters to just one considering the existence of `IntoSystemDescriptor<Params>`. we can use `impl IntoSystemDescriptor<Params>` which removes one of the generics, but it's not clear to me how you'd remove that `Params` generic without boxing
