### ISSUE TITLE
Command systems run all the time

### ISSUE THREAD

**Issue by makspll** [RichoDemus/bevy-console#20]
Currently the system provided to `add_console_command` run every frame, this seems inefficient to me, 
would it be possible instead to run these systems only when the command event fires instead ?

**Comment by jopkashmelya** [comment]
Currently in bevy every system runs every frame

**Comment by brandon-reinhart** [comment]
iyes_loopless could give you a way to manage conditional execution of systems

**Comment by makspll** [comment]
I was thinking some sort of run condition which checks if there are outstanding console events, before running the possibly many console systems would be preferable, albeit it would be a small performance improvement

**Comment by makspll** [comment]
Closed in #41
