### ISSUE TITLE
Is it possible to hook info! etc and send to the console?

### ISSUE THREAD

**Issue by brandon-reinhart** [RichoDemus/bevy-console#23]
I'd like to be able to pipe all the standard bevy output to the console. Is there a way to do that?

**Comment by brandon-reinhart** [comment]
Looks like it might be if Bevy provided a way to modify the tracing subscriber. At the moment, the only alternative is to provide a custom tracing subscriber.

**Comment by makspll** [comment]
It would be nice to have some sort of "hook" or multiple subscribers indeed

**Comment by brandon-reinhart** [comment]
Some research here.

Bevy installs a tracing subscriber in bevy::log::LogPlugin. A tracing subscriber consists of layers, each of which get a chance to modify what is traced or how the trace is handled. Bevy's subscriber uses a fmt layer which outputs log Records to stdout. Bevy also uses LogTracer which directs log macros like info! to create tracing Records.

info! -> Record -> fmt Layer -> stdout

I believe tracing only supports one subscriber, so if you want to direct records to the console you need to install a layer. Once the subscriber is set, you can't add a new layer to it.

This means this task decomposes into:

    Author a Subscriber & Layer similar to tracing_subscriber::fmt which handles Records for the console.
    Modify Bevy to allow for third party layers prior to installation of the global default subscriber.

**Comment by johanhelsing** [comment]
I had a go at making bevy able to inject extra log layers: https://github.com/bevyengine/bevy/pull/7682

The PR has some issues, because plugin `build` can't take ownership of their parameters at the moment.

The pr has an example which should get you pretty close to this however.

I'm not currently working on the PR, just thought I'd share if someone wants to pick it up.

**Comment by sbaranov** [comment]
While log layer support is being worked on, did anybody manage to at least redirect the regular println! to bevy-console?

**Comment by brandon-reinhart** [comment]
FWIW, I think this is possible now.

**Comment by brandon-reinhart** [comment]
I investigated this, looks like we're going to need a small adjustment that's in bevy main in order to direct custom subscriber events to the ECS. Then it will be easy to have a system that can scoop this into the console.

**Comment by makspll** [comment]
I think it is, I got an example working with a custom layer and a buffer resource

**Comment by makspll** [comment]
![image](https://github.com/user-attachments/assets/14878d5c-dddf-44e5-b5c4-5a4d619fef44)

**Comment by johanhelsing** [comment]
Oooo... Do you think you could share the code for it?

**Comment by makspll** [comment]
Yeah, I will likely put up a PR today
