### ISSUE TITLE
Fork proposal.

### ISSUE THREAD

**Issue by brandon-reinhart** [RichoDemus/bevy-console#26]
RichoDemus appears to be inactive. I'm not sure what his Discord is, so couldn't DM him.

I'm proposing a fork of bevy-console in order to move the project forward. However, I want to make sure this is done with due respect and acknowledgment to RichoDemus and out of the understanding that we appreciate the project and want to keep it alive.

Initial goals of the fork:
- Ship a crate compatible with Bevy 0.8
- Review and triage previous issues.
- Pursue a re-license under MIT / Apache 2.0

This will sit here for at least 7 days to gather comments.

**Comment by makspll** [comment]
I am for this, I've been wanting to port my old examples but couldn't and I think this crate could do with a little maintenance considering many outstanding issues,

I was literally about to consider doing something about this as I came across this issue.

I would suggest a more preferable course of action should Richo come back in due time:
- we wait a bit for @RichoDemus to come back and ask for merge rights for some new contributors
this course of action would avoid splitting the ecosystem and credit the original author better.

However should Richo not come back in due time I don't see a good alternative.

**Comment by RichoDemus** [comment]
Hey, sorry for being absent. I’m struggling with a burnout right now so I’ve quite neglectful, I’m all up for adding some people as maintainers and sharing the credentials to upload new versions or transferring ownership. I don’t know which is the best approach. I’ll try my best to monitor this thread

sorry and thanks for the enthusiasm

**Comment by makspll** [comment]
@RichoDemus absolutely no worries! You've provided the community with a great package and no apologies necessary, such is the nature of open source!

I am happy to volunteer as one of new contributors, I imagine @brandon-reinhart would be happy to accept cargo credentials?

**Comment by brandon-reinhart** [comment]
I am willing to volunteer as a contributor or do whatever else is helpful!

**Comment by brandon-reinhart** [comment]
@RichoDemus - You can email me brandon@encultured.ai if you want to talk about cargo credentials.

I went ahead and merged the 0.8 fixes into main.

**Comment by makspll** [comment]
@RichoDemus thank you for the contributor rights! I suppose this issue can be closed now then!
