### ISSUE TITLE
Couldn't satisfy dependencies of my project with bevy-console = "0.4.0"

### ISSUE THREAD

**Issue by xxxxxion** [RichoDemus/bevy-console#35]
Hello,
I've recently tried to add bevy-console to my Cargo.toml , and then i've go an error message : 
![bug_bev](https://user-images.githubusercontent.com/98020041/204834163-9ca0228d-e988-4dc2-b798-280fcb3d5f7b.png)

I find out, that if i add bevy with disabled default-features : 
`bevy = { version =  "0.9.0", default-features = false }`
It let me build, but anyway of course it fails to build. Could you suggest something ?

Also this is whole Cargo.toml file: 
![image](https://user-images.githubusercontent.com/98020041/204839230-dbd1c85d-b2af-4f0d-bc8c-0a582c0eaead.png)

**Comment by makspll** [comment]
`bevy_console` 0.4 depends on `bevy` 0.8. The error is telling you that cargo cannot reconcile the two versions of bevy, specifically some dependency of bevy at once. 

support for bevy 0.9 only exists on the main branch of this crate so far, a release hasn't been made yet. What you could do is use:
`bevy = { git="https://github.com/RichoDemus/bevy-console" }`
 in your cargo file for now.

I am not sure why adding the bevy 0.9 version as a direct dependency helps here. Does this help?

**Comment by xxxxxion** [comment]
Yes, that helped me. My bad, i saw Cargo.toml at main branch and saw that it deps on bevy=0.9.

Also you made typo - you mean 
bevy_console = { git = "...

**Comment by makspll** [comment]
No problem at all, ah yes thank you!
