### ISSUE TITLE
Update crates.io published code to support bevy 0.9

### ISSUE THREAD

**Issue by wallamide** [RichoDemus/bevy-console#36]
Currently adding `bevy_console` 0.4 to a cargo file using `bevy` 0.9  results in this rust-analyzer message:

```
Previously selected package `notify v5.0.0-pre.15`
    ... which satisfies dependency `notify = "=5.0.0-pre.15"` of package `bevy_asset v0.8.1`
    ... which satisfies dependency `bevy_asset = "^0.8.0"` of package `bevy_internal v0.8.0`
    ... which satisfies dependency `bevy_internal = "^0.8.0"` of package `bevy v0.8.0`
    ... which satisfies dependency `bevy = "^0.8.0"` of package `bevy_console v0.4.0`
    ... which satisfies dependency `bevy_console = "^0.4.0"` of package `debug_tools v0.0.2 
```
and the crates.io page shows the last update as 4 months ago.

**Comment by makspll** [comment]
Yes crates.io does not have the current version of this crate, unfortunately I do not have the rights to release it only @brandon-reinhart and the original owner do.

**Comment by makspll** [comment]
I've now gotten the token, happy to report version 0.5.0 is now live

**Comment by wallamide** [comment]
Thanks for this!

**Comment by makspll** [comment]
No problem! Happy to help
