### ISSUE TITLE
Possible licensing issue

### ISSUE THREAD

**Issue by TimJentzsch** [RichoDemus/bevy-console#38]
`bevy_console_parser` depends on [`nom-supreme`](https://github.com/Lucretiel/nom-supreme), which is licensed with `MPL-2.0`.
This is a copyleft license, and as far as I understand it, it requires you to distribute your library under the same license.

`bevy-console` uses the MIT license, which probably doesn't comply with the MPL licensing terms.

This issue was discovered using [`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny) in a project that depends on `bevy-console`.

**Comment by makspll** [comment]
Hmm, we should probably stop using `nom-supreme` in this case. If #37 gets done this kills two birds with one stone I suppose

**Comment by makspll** [comment]
Should be fixed in next release
