### ISSUE TITLE
Wrong command called problem!

### ISSUE THREAD

**Issue by zzhgithub** [RichoDemus/bevy-console#54]
![image](https://github.com/RichoDemus/bevy-console/assets/12131877/dae3a63c-16b3-4db5-bf34-1b6afa9289d9)
 I add a command named 'mesh_state'.
but when i enter help or mesh_state itself. now it run two times? Why?

**Comment by zzhgithub** [comment]
Here are codes:
```rust
impl Plugin for ConsoleCommandPlugins {
    fn build(&self, app: &mut App) {
        app.add_plugins(ConsolePlugin)
            .add_systems(PreUpdate, sync_flags)
            .add_systems(Update, raw_commands.in_set(ConsoleSet::Commands))
            .add_console_command::<MeshStateCommand, _>(check_mesh_state);
    }
}

// 保持打开时不能操作人物
fn sync_flags(mut controller_flag: ResMut<ControllerFlag>, console_open: Res<ConsoleOpen>) {
    controller_flag.flag = !console_open.open;
}

fn raw_commands(mut console_commands: EventReader<ConsoleCommandEntered>) {
    for ConsoleCommandEntered { command_name, args } in console_commands.iter() {
        println!(r#"Entered command "{command_name}" with args {:#?}"#, args);
    }
}

```

```rust

#[derive(Parser, ConsoleCommand)]
#[command(
    name = "mesh_state",
    about = "check the state of the mesh on current clip_shperer"
)]
pub struct MeshStateCommand;

pub fn check_mesh_state(
    mut mesh_state_command: ConsoleCommand<MeshStateCommand>,
    clip_spheres: Res<ClipSpheres>,
    mesh_manager: Res<MeshManager>,
    chunk_map: Res<ChunkMap>,
) {
    // something impl
}
```

**Comment by makspll** [comment]
Hi, does the command system actually run twice, or is it that `ok` is printed twice ?

**Comment by makspll** [comment]
Also please try run with debug level logging and show the output

**Comment by zzhgithub** [comment]
![image](https://github.com/RichoDemus/bevy-console/assets/12131877/d9acc0c7-c30d-4f7a-b561-88742f8c5845)
It really run twice. and when i use command help.my build command also run .

**Comment by zzhgithub** [comment]
do you need my code . here is https://github.com/zzhgithub/just_join_v2
and I do not think there is some spiceal in my  project.

**Comment by zzhgithub** [comment]
And I found sometimes i can not press KeyCode:H in console or just can not press any KeyCode. Why?

**Comment by makspll** [comment]
Hi @zzhgithub could you provide a minimal project which reproduces this, I do not see anything in the systems provided which would cause this behavior.
