### ISSUE TITLE
Can we not fix the version of clap?

### ISSUE THREAD

**Issue by darkclouder** [RichoDemus/bevy-console#55]
Hey there, I would love to use this package but the version of clap is fixed and not up-to-date. Can't you set that without the equal sign and make the clap version more flexible or are you using some internal things that don't allow you to update it?

Edit: I changed it in a fork and it works like a charm. So maybe we can just drop the `=` in `=X.Y.Z` for clap?

**Comment by makspll** [comment]
Hey there, yeah that should be fine :)
