### ISSUE TITLE
Update `bevy_egui` to v0.24

### ISSUE THREAD

**Issue by umut-sahin** [RichoDemus/bevy-console#60]
When `bevy-console` is used with [bevy-inspector-egui](https://github.com/jakobhellermann/bevy-inspector-egui/), adding the console plugin crashes with:
```
Error adding plugin bevy_egui::EguiPlugin: : plugin was already added in application
```

I think the reason for this is that both `v0.23` and `v0.24` gets included in the build and somehow this check fails: https://github.com/RichoDemus/bevy-console/blob/44d431c04acfb1c853e807371639cede254be414/src/lib.rs#L77-L81

I'm not 100% sure that it'll solve the issue but I think it's worth a try!

**Comment by makspll** [comment]
Could you try the current version on the main brunch?

**Comment by umut-sahin** [comment]
It's working!

**Comment by makspll** [comment]
Nice! I'll release this version

**Comment by umut-sahin** [comment]
Thanks for the quick resolution, looking forward to use the library :partying_face:

**Comment by makspll** [comment]
no worries :)
