### ISSUE TITLE
Please add a config option to NOT init the egui plugin 

### ISSUE THREAD

**Issue by ethereumdegen** [RichoDemus/bevy-console#61]
thread 'main' panicked at src/world_interaction/dialog.rs:10:9:
Error adding plugin bevy_egui::EguiPlugin: : plugin was already added in application
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrac

**Comment by 00alia00** [comment]
This might be caused by 2 different versions of Egui.. (I had the same issue) check your Cargo.lock?

**Comment by ethereumdegen** [comment]
nope.. still getting this 
thread 'main' panicked at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_console-0.11.1/src/lib.rs:80:17:
Error adding plugin bevy_egui::EguiPlugin: : plugin was already added in application
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


see how bevy_inspector_egui handles this .  ...

if !app.is_plugin_added::<DefaultInspectorConfigPlugin>() {
            app.add_plugins(DefaultInspectorConfigPlugin);
        }
        if !app.is_plugin_added::<EguiPlugin>() {
            app.add_plugins(EguiPlugin);
        }
